build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY:
      secure: mw1Fz5a5C0lT4CXzsOCADoo/Xa9YymZI3yjVZNR8f5GwYrVAOC2YXxyEG6NaSWZY
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.4

matrix:
  fast_finish: true

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/menpo/condaci/v0.4.6/condaci.py' C:\\condaci.py; echo "Done"
- cmd: python C:\\condaci.py setup

install:
- cmd: set tmp_cmd=python C:\\condaci.py miniconda_dir
- cmd: "FOR /F %%i IN (' %tmp_cmd% ') DO SET APPV_MINICONDA_DIR=%%i"
- cmd: set APPV_MINICONDA_EXE="%APPV_MINICONDA_DIR%\python.exe"
- cmd: "%APPV_MINICONDA_EXE% C:\\condaci.py build conda"

notifications:
  - provider: Slack
    auth_token:
      secure: Jyd2NTPkBrrwBnl1C0mkNp5sUPGXzKrDgpZVDvPj72OUJtovXsO3795UsvktLucG
    channel: general
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false

