version: 2

workflows:
  version: 2
  test:
    jobs:
      - linux_python_3.8:
          context:
            - menpo
      - linux_python_3.9:
          filters:
            tags:
              only: /.*/
          context:
            - menpo
      - linux_python_3.10:
          context:
            - menpo

template: &linux_template
  resource_class: medium+
  docker:
    - image: circleci/python:latest
  steps:
    - checkout
    - run:
        name: Setup Miniconda
        command: |
          wget https://raw.githubusercontent.com/menpo/condaci/circleci/condaci.py -O condaci.py
          python condaci.py setup --channels conda-forge
    - run:
        name: Run conda build
        command: |
          ~/miniconda/bin/python condaci.py build ./conda

jobs:
  linux_python_3.8:
    <<: *linux_template
    environment:
      CONDACI_PYPI_SDIST_UPLOAD_PY_VER: 3.9
      PYTHON_VERSION: 3.8
  linux_python_3.9:
    <<: *linux_template
    environment:
      CONDACI_PYPI_SDIST_UPLOAD_PY_VER: 3.9
      PYTHON_VERSION: 3.9
  linux_python_3.10:
    <<: *linux_template
    environment:
      CONDACI_PYPI_SDIST_UPLOAD_PY_VER: 3.9
      PYTHON_VERSION: "3.10"