name: menpo_rtd
channels:
  - menpo
dependencies:
  - python
  - setuptools
  - numpy >=1.10,<1.11
  - cython 0.23.*
  - pathlib 1.0

  - numpy >=1.10,<1.11
  - scipy 0.16.*
  - pillow  3.0.*
  - cyvlfeat >=0.4.2,<0.5
  - matplotlib >=1.4,<1.6
  - mock 1.3.*
  - nose
  - pip:
      - sphinx==1.3.1
      - sphinx_rtd_theme==0.1.7
      - sphinxmapxrefrole==0.2.1

